#![doc = include_str!("../README.md")]
#![doc = "\n\n"]
#![doc = include_str!("../SYNTAX.md")]

// src/lib.rs

// Re-export the macro
pub use winnow_grammar_macros::grammar;

// Re-export winnow so generated code has access to it
pub use winnow;

use std::sync::Arc;
use lasso::{ThreadedRodeo, Spur};

// Re-export the core types for the user.
pub type Symbol = Spur;
pub type InternerContext = ThreadedRodeo;

/// The shared context that is passed as state to the parser.
///
/// It contains the thread-safe string interner and a placeholder for any user-defined state.
#[derive(Debug, Clone)]
pub struct ParseContext<S = ()> {
    /// A thread-safe, shared string interner.
    pub interner: Arc<InternerContext>,
    /// A placeholder for user-defined state.
    pub user_state: S,
}

impl<S: Default> Default for ParseContext<S> {
    fn default() -> Self {
        Self {
            interner: Arc::new(InternerContext::new()),
            user_state: S::default(),
        }
    }
}

/// The input stream type used by all parsers generated by the `grammar!` macro.
///
/// It combines the input string slice with the shared `ParseContext`.
pub type ParseInput<'a, S = ()> = ::winnow::stream::Stateful<::winnow::stream::LocatingSlice<&'a str>, ParseContext<S>>;


// Re-export testing utilities
pub mod testing;

/// Portable types for backend compatibility
pub mod types {
    use proc_macro2::TokenStream;
    use quote::ToTokens;
    use std::fmt;
    use std::hash::{Hash, Hasher};

    pub use grammar_kit::WithSpan;
    pub use proc_macro2::Span;

    /// A generic wrapper that attaches a source span to a value.
    #[derive(Clone, Copy)]
    pub struct SpannedValue<T> {
        pub value: T,
        pub span: Span,
    }

    impl<T> SpannedValue<T> {
        pub fn new(value: T, span: Span) -> Self {
            Self { value, span }
        }
    }

    impl<T: PartialEq> PartialEq for SpannedValue<T> {
        fn eq(&self, other: &Self) -> bool {
            self.value == other.value
        }
    }

    impl<T: Eq> Eq for SpannedValue<T> {}

    impl<T: Hash> Hash for SpannedValue<T> {
        fn hash<H: Hasher>(&self, state: &mut H) {
            self.value.hash(state);
        }
    }

    impl<T: fmt::Display> fmt::Display for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            self.value.fmt(f)
        }
    }

    impl<T: fmt::Debug> fmt::Debug for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("SpannedValue")
                .field("value", &self.value)
                .field("span", &self.span)
                .finish()
        }
    }

    impl<T: ToTokens> ToTokens for SpannedValue<T>
    where
        T: ToTokens,
    {
        fn to_tokens(&self, tokens: &mut TokenStream) {
            self.value.to_tokens(tokens);
        }
    }
}

pub use types::{SpannedValue, WithSpan};
