#![doc = include_str!("../README.md")]
#![doc = "\n\n"]
#![doc = include_str!("../SYNTAX.md")]

// src/lib.rs

// Re-export the macro
pub use winnow_grammar_macros::grammar;

// Re-export winnow so generated code has access to it
pub use winnow;

/// The error type of the generated parsers and the selection between errors.
pub mod error;
pub mod interner;
/// Runtime helpers for the generated code.
pub mod rt;
pub mod test_result;
pub mod testing;

pub use error::{ParseError, PRIO_AGGREGATED, PRIO_LABELED, PRIO_NORMAL, PRIO_STRUCTURAL};

pub use interner::{InternerContext, Symbol};

/// The shared context that is passed as state to the parser.
///
/// It contains the thread-safe string interner and a placeholder for any user-defined state.
#[derive(Debug, Clone)]
pub struct ParseContext<S = ()> {
    /// A thread-safe, shared string interner.
    pub interner: InternerContext,
    /// A placeholder for user-defined state.
    pub user_state: S,
    /// The furthest failure position that a successful backtrack (`x?`, `x*`)
    /// discarded. Compared against the returned error at the end - see
    /// [`crate::rt::finish`].
    pub furthest: Option<ParseError>,
    /// The **live** rule stack: the rules currently running, outermost first.
    /// An error that is passed out collects its rules itself on the way back;
    /// an error that is *recorded* along the way never gets there - it
    /// receives the outer rules from here.
    pub rules: Vec<&'static str>,
}

impl<S: Default> Default for ParseContext<S> {
    fn default() -> Self {
        Self {
            interner: InternerContext::new(),
            user_state: S::default(),
            furthest: None,
            rules: Vec::new(),
        }
    }
}

impl<S> ParseContext<S> {
    /// Records a discarded error - following the same ranking as
    /// [`ParseError::merge`].
    pub fn record(&mut self, e: &ParseError) {
        let mut e = e.clone();
        for r in self.rules.iter().rev() {
            e.push_rule(r);
        }
        self.furthest = Some(match self.furthest.take() {
            Some(f) => f.merge(e),
            None => e,
        });
    }

    /// The better of the returned error and the recorded one.
    pub fn best(&self, e: ParseError) -> ParseError {
        match &self.furthest {
            Some(f) => f.clone().merge(e),
            None => e,
        }
    }
}

/// The input stream type used by all parsers generated by the `grammar!` macro.
///
/// It combines the input string slice with the shared `ParseContext`.
pub type ParseInput<'a, S = ()> =
    ::winnow::stream::Stateful<::winnow::stream::LocatingSlice<&'a str>, ParseContext<S>>;

pub mod types {
    use proc_macro2::TokenStream;
    use quote::ToTokens;
    use std::fmt;
    use std::hash::{Hash, Hasher};

    pub use proc_macro2::Span;

    /// Constructs a value from parsed data and the position where it was found.
    ///
    /// Implemented by the attribute macro [`with_span`](winnow_grammar_macros::with_span).
    /// Formerly obtained from `grammar-kit`; moved here during the move out of
    /// the syn-grammar monorepo so that `winnow-grammar` no longer needs a
    /// dependency on the syn-side runtime.
    pub trait WithSpan<ParsedData> {
        /// Builds `Self` from `parsed_data` and the byte range `span`.
        fn with_span(parsed_data: ParsedData, span: std::ops::Range<usize>) -> Self;
    }

    /// A generic wrapper that attaches a source span to a value.
    #[derive(Clone, Copy)]
    pub struct SpannedValue<T> {
        pub value: T,
        pub span: Span,
    }

    impl<T> SpannedValue<T> {
        pub fn new(value: T, span: Span) -> Self {
            Self { value, span }
        }
    }

    impl<T: PartialEq> PartialEq for SpannedValue<T> {
        fn eq(&self, other: &Self) -> bool {
            self.value == other.value
        }
    }

    impl<T: Eq> Eq for SpannedValue<T> {}

    impl<T: Hash> Hash for SpannedValue<T> {
        fn hash<H: Hasher>(&self, state: &mut H) {
            self.value.hash(state);
        }
    }

    impl<T: fmt::Display> fmt::Display for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            self.value.fmt(f)
        }
    }

    impl<T: fmt::Debug> fmt::Debug for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("SpannedValue")
                .field("value", &self.value)
                .field("span", &self.span)
                .finish()
        }
    }

    impl<T: ToTokens> ToTokens for SpannedValue<T>
    where
        T: ToTokens,
    {
        fn to_tokens(&self, tokens: &mut TokenStream) {
            self.value.to_tokens(tokens);
        }
    }
}

pub use types::{SpannedValue, WithSpan};
