#![doc = include_str!("../README.md")]
#![doc = "\n\n"]
#![doc = include_str!("../SYNTAX.md")]

// src/lib.rs

// Re-export the macro
pub use winnow_grammar_macros::grammar;

// Re-export winnow so generated code has access to it
pub use winnow;

/// Der Fehlertyp der erzeugten Parser und die Auswahl zwischen Fehlern.
pub mod error;
pub mod interner;
/// Laufzeithelfer fuer den erzeugten Code.
pub mod rt;
pub mod test_result;
pub mod testing;

pub use error::{ParseError, PRIO_AGGREGATED, PRIO_LABELED, PRIO_NORMAL, PRIO_STRUCTURAL};

pub use interner::{InternerContext, Symbol};

/// The shared context that is passed as state to the parser.
///
/// It contains the thread-safe string interner and a placeholder for any user-defined state.
#[derive(Debug, Clone)]
pub struct ParseContext<S = ()> {
    /// A thread-safe, shared string interner.
    pub interner: InternerContext,
    /// A placeholder for user-defined state.
    pub user_state: S,
    /// Die weiteste Fehlschlagstelle, die ein erfolgreiches Zuruecksetzen
    /// (`x?`, `x*`) verworfen hat. Wird am Ende gegen den zurueckgegebenen
    /// Fehler gehalten - siehe [`crate::rt::abschluss`].
    pub furthest: Option<ParseError>,
    /// Der **lebende** Regelstapel: die Regeln, die gerade laufen, aeusserste
    /// zuerst. Ein Fehler, der herausgereicht wird, sammelt seine Regeln auf
    /// dem Rueckweg selbst; ein Fehler, der unterwegs *gemerkt* wird, kommt
    /// dort nie vorbei - er bekommt die aeusseren Regeln von hier.
    pub regeln: Vec<&'static str>,
}

impl<S: Default> Default for ParseContext<S> {
    fn default() -> Self {
        Self {
            interner: InternerContext::new(),
            user_state: S::default(),
            furthest: None,
            regeln: Vec::new(),
        }
    }
}

impl<S> ParseContext<S> {
    /// Merkt einen verworfenen Fehler - nach derselben Rangfolge wie
    /// [`ParseError::merge`].
    pub fn merke(&mut self, e: &ParseError) {
        let mut e = e.clone();
        for r in self.regeln.iter().rev() {
            e.push_rule(r);
        }
        self.furthest = Some(match self.furthest.take() {
            Some(f) => f.merge(e),
            None => e,
        });
    }

    /// Der bessere aus zurueckgegebenem Fehler und Merkstelle.
    pub fn beste(&self, e: ParseError) -> ParseError {
        match &self.furthest {
            Some(f) => f.clone().merge(e),
            None => e,
        }
    }
}

/// The input stream type used by all parsers generated by the `grammar!` macro.
///
/// It combines the input string slice with the shared `ParseContext`.
pub type ParseInput<'a, S = ()> =
    ::winnow::stream::Stateful<::winnow::stream::LocatingSlice<&'a str>, ParseContext<S>>;

pub mod types {
    use proc_macro2::TokenStream;
    use quote::ToTokens;
    use std::fmt;
    use std::hash::{Hash, Hasher};

    pub use proc_macro2::Span;

    /// Konstruiert einen Wert aus geparsten Daten und der Stelle, an der sie standen.
    ///
    /// Wird vom Attributmakro [`with_span`](winnow_grammar_macros::with_span)
    /// implementiert. Frueher aus `grammar-kit` bezogen; beim Auszug aus dem
    /// syn-grammar-Monorepo hierher uebernommen, damit `winnow-grammar` keine
    /// Abhaengigkeit auf die syn-seitige Laufzeit mehr braucht.
    pub trait WithSpan<ParsedData> {
        /// Baut `Self` aus `parsed_data` und dem Byte-Bereich `span`.
        fn with_span(parsed_data: ParsedData, span: std::ops::Range<usize>) -> Self;
    }

    /// A generic wrapper that attaches a source span to a value.
    #[derive(Clone, Copy)]
    pub struct SpannedValue<T> {
        pub value: T,
        pub span: Span,
    }

    impl<T> SpannedValue<T> {
        pub fn new(value: T, span: Span) -> Self {
            Self { value, span }
        }
    }

    impl<T: PartialEq> PartialEq for SpannedValue<T> {
        fn eq(&self, other: &Self) -> bool {
            self.value == other.value
        }
    }

    impl<T: Eq> Eq for SpannedValue<T> {}

    impl<T: Hash> Hash for SpannedValue<T> {
        fn hash<H: Hasher>(&self, state: &mut H) {
            self.value.hash(state);
        }
    }

    impl<T: fmt::Display> fmt::Display for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            self.value.fmt(f)
        }
    }

    impl<T: fmt::Debug> fmt::Debug for SpannedValue<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("SpannedValue")
                .field("value", &self.value)
                .field("span", &self.span)
                .finish()
        }
    }

    impl<T: ToTokens> ToTokens for SpannedValue<T>
    where
        T: ToTokens,
    {
        fn to_tokens(&self, tokens: &mut TokenStream) {
            self.value.to_tokens(tokens);
        }
    }
}

pub use types::{SpannedValue, WithSpan};
